// <auto-generated />
using System;
using CourseSystem_DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseSystem_DAL.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20250412194723_m01")]
    partial class m01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseSystem_DAL.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e33dd1b-3a4d-48f5-84c1-565170287dbf"),
                            DepartmentId = new Guid("045e90a9-bd08-45ae-80c7-fa8ee939fd74"),
                            Duration = 4,
                            InstructorId = new Guid("0e65f178-8ad3-442b-859f-48d6d964b044"),
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("2ce2280b-8172-4045-8bdc-270794694177"),
                            DepartmentId = new Guid("c11ea3d8-7da5-44bd-a313-e1a6fbafad79"),
                            Duration = 5,
                            InstructorId = new Guid("30a2d33f-c405-4b72-a7ad-b21e630ada5e"),
                            Name = "Java 0Script"
                        },
                        new
                        {
                            Id = new Guid("5ef659b6-d082-41d0-8f5d-984d883a3482"),
                            DepartmentId = new Guid("cb84409a-44b6-49fa-8a67-92ae33862119"),
                            Duration = 6,
                            InstructorId = new Guid("8c8e5e8e-2210-4c96-9a78-51f66471627b"),
                            Name = "Secuirety"
                        },
                        new
                        {
                            Id = new Guid("f78d5fdf-66b7-44be-b9f2-1e42be682a74"),
                            DepartmentId = new Guid("d5b7c05f-4fbf-44c3-b181-2176aa8ea9e2"),
                            Duration = 7,
                            InstructorId = new Guid("a7405fe2-f9ff-488c-937b-ff60e3e9c24d"),
                            Name = "Flutter"
                        },
                        new
                        {
                            Id = new Guid("fe17271a-1f45-4a17-b661-30fc9b377f98"),
                            DepartmentId = new Guid("d67ae4ea-6fb4-4dbd-af73-90192db76b5a"),
                            Duration = 8,
                            InstructorId = new Guid("b6e66f14-8e6d-4c03-9c12-753ed9e4f74d"),
                            Name = "Azure"
                        });
                });

            modelBuilder.Entity("CourseSystem_DAL.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("045e90a9-bd08-45ae-80c7-fa8ee939fd74"),
                            ManagerId = new Guid("0e65f178-8ad3-442b-859f-48d6d964b044"),
                            Name = "SD"
                        },
                        new
                        {
                            Id = new Guid("c11ea3d8-7da5-44bd-a313-e1a6fbafad79"),
                            ManagerId = new Guid("30a2d33f-c405-4b72-a7ad-b21e630ada5e"),
                            Name = "UI"
                        },
                        new
                        {
                            Id = new Guid("cb84409a-44b6-49fa-8a67-92ae33862119"),
                            ManagerId = new Guid("8c8e5e8e-2210-4c96-9a78-51f66471627b"),
                            Name = "Network"
                        },
                        new
                        {
                            Id = new Guid("d5b7c05f-4fbf-44c3-b181-2176aa8ea9e2"),
                            ManagerId = new Guid("a7405fe2-f9ff-488c-937b-ff60e3e9c24d"),
                            Name = "Mobile"
                        },
                        new
                        {
                            Id = new Guid("d67ae4ea-6fb4-4dbd-af73-90192db76b5a"),
                            ManagerId = new Guid("b6e66f14-8e6d-4c03-9c12-753ed9e4f74d"),
                            Name = "Cloud"
                        });
                });

            modelBuilder.Entity("CourseSystem_DAL.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e65f178-8ad3-442b-859f-48d6d964b044"),
                            FirstName = "Mohamed",
                            LastName = "Ziad",
                            Phone = "01120210123"
                        },
                        new
                        {
                            Id = new Guid("30a2d33f-c405-4b72-a7ad-b21e630ada5e"),
                            FirstName = "Basem",
                            LastName = "Ahmed",
                            Phone = "01020210541"
                        },
                        new
                        {
                            Id = new Guid("8c8e5e8e-2210-4c96-9a78-51f66471627b"),
                            FirstName = "Ahmed",
                            LastName = "Omer",
                            Phone = "01020210789"
                        },
                        new
                        {
                            Id = new Guid("a7405fe2-f9ff-488c-937b-ff60e3e9c24d"),
                            FirstName = "Amr",
                            LastName = "Mohamed",
                            Phone = "01520210246"
                        },
                        new
                        {
                            Id = new Guid("b6e66f14-8e6d-4c03-9c12-753ed9e4f74d"),
                            FirstName = "Ali",
                            LastName = "Basem",
                            Phone = "01220210456"
                        },
                        new
                        {
                            Id = new Guid("c8b09a7f-0c3a-4a97-b586-55f23cfed9a6"),
                            FirstName = "Omer",
                            LastName = "Ali",
                            Phone = "01220210897"
                        },
                        new
                        {
                            Id = new Guid("e44c2c5d-9de9-45b4-814a-03169fc4edd1"),
                            FirstName = "Ziad",
                            LastName = "Amr",
                            Phone = "01120210827"
                        });
                });

            modelBuilder.Entity("CourseSystem_DAL.Models.CourseSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("CourseSessions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("217c3d9a-dda7-40ea-b9a2-a0d980c97a17"),
                            CourseId = new Guid("1e33dd1b-3a4d-48f5-84c1-565170287dbf"),
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = new Guid("0e65f178-8ad3-442b-859f-48d6d964b044"),
                            Title = "title1"
                        },
                        new
                        {
                            Id = new Guid("30308204-257c-43a3-b0a8-c18229693a15"),
                            CourseId = new Guid("1e33dd1b-3a4d-48f5-84c1-565170287dbf"),
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = new Guid("0e65f178-8ad3-442b-859f-48d6d964b044"),
                            Title = "title2"
                        },
                        new
                        {
                            Id = new Guid("739444d1-a7c9-4842-a421-7f6e4aa00050"),
                            CourseId = new Guid("2ce2280b-8172-4045-8bdc-270794694177"),
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = new Guid("30a2d33f-c405-4b72-a7ad-b21e630ada5e"),
                            Title = "title3"
                        },
                        new
                        {
                            Id = new Guid("a0054941-4cfc-4e01-a786-0b6eba49e257"),
                            CourseId = new Guid("2ce2280b-8172-4045-8bdc-270794694177"),
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = new Guid("30a2d33f-c405-4b72-a7ad-b21e630ada5e"),
                            Title = "title4"
                        },
                        new
                        {
                            Id = new Guid("ef7d718d-c2ea-4a19-b7d8-c2a2469b0598"),
                            CourseId = new Guid("5ef659b6-d082-41d0-8f5d-984d883a3482"),
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = new Guid("b6e66f14-8e6d-4c03-9c12-753ed9e4f74d"),
                            Title = "title5"
                        },
                        new
                        {
                            Id = new Guid("efe3251e-c1de-4fe1-89f1-be9000a3be78"),
                            CourseId = new Guid("5ef659b6-d082-41d0-8f5d-984d883a3482"),
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = new Guid("b6e66f14-8e6d-4c03-9c12-753ed9e4f74d"),
                            Title = "title6"
                        });
                });

            modelBuilder.Entity("CourseSystem_DAL.Models.CourseSessionAttendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseSessionId");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseSessionAttendances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("217c3d9a-dda7-40ea-b9a2-a0d980c97a11"),
                            CourseSessionId = new Guid("217c3d9a-dda7-40ea-b9a2-a0d980c97a17"),
                            Grade = 33,
                            Notes = "note1",
                            StudentId = new Guid("3670be78-8f4d-4bbe-b612-3f628e497896")
                        },
                        new
                        {
                            Id = new Guid("217c3d9a-dda7-40ea-b9a2-a0d980c97a12"),
                            CourseSessionId = new Guid("30308204-257c-43a3-b0a8-c18229693a15"),
                            Grade = 44,
                            Notes = "note2",
                            StudentId = new Guid("3670be78-8f4d-4bbe-b612-3f628e497896")
                        },
                        new
                        {
                            Id = new Guid("217c3d9a-dda7-40ea-b9a2-a0d980c97a13"),
                            CourseSessionId = new Guid("739444d1-a7c9-4842-a421-7f6e4aa00050"),
                            Grade = 55,
                            Notes = "note3",
                            StudentId = new Guid("3670be78-8f4d-4bbe-b612-3f628e497896")
                        },
                        new
                        {
                            Id = new Guid("217c3d9a-dda7-40ea-b9a2-a0d980c97a14"),
                            CourseSessionId = new Guid("a0054941-4cfc-4e01-a786-0b6eba49e257"),
                            Grade = 66,
                            Notes = "note4",
                            StudentId = new Guid("3670be78-8f4d-4bbe-b612-3f628e497896")
                        },
                        new
                        {
                            Id = new Guid("217c3d9a-dda7-40ea-b9a2-a0d980c97a15"),
                            CourseSessionId = new Guid("ef7d718d-c2ea-4a19-b7d8-c2a2469b0598"),
                            Grade = 77,
                            Notes = "note5",
                            StudentId = new Guid("3670be78-8f4d-4bbe-b612-3f628e497896")
                        },
                        new
                        {
                            Id = new Guid("217c3d9a-dda7-40ea-b9a2-a0d980c97a16"),
                            CourseSessionId = new Guid("efe3251e-c1de-4fe1-89f1-be9000a3be78"),
                            Grade = 88,
                            Notes = "note6",
                            StudentId = new Guid("3670be78-8f4d-4bbe-b612-3f628e497896")
                        });
                });

            modelBuilder.Entity("CourseSystem_DAL.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3670be78-8f4d-4bbe-b612-3f628e497896"),
                            FirstName = "Mohamed",
                            LastName = "Ziad",
                            Phone = "01120210123"
                        },
                        new
                        {
                            Id = new Guid("67fd4e60-40f4-4842-97fa-8c331f862dcf"),
                            FirstName = "Basem",
                            LastName = "Ahmed",
                            Phone = "01020210541"
                        },
                        new
                        {
                            Id = new Guid("7cadd23b-7b0a-4dab-9d32-9c2c1570caa4"),
                            FirstName = "Ahmed",
                            LastName = "Omer",
                            Phone = "01020210789"
                        },
                        new
                        {
                            Id = new Guid("d69770e1-71a0-4ed8-b2eb-cc54fa78e46c"),
                            FirstName = "Amr",
                            LastName = "Mohamed",
                            Phone = "01520210246"
                        },
                        new
                        {
                            Id = new Guid("eef11cbc-ef8c-4224-bc4a-e735412d10ea"),
                            FirstName = "Ali",
                            LastName = "Basem",
                            Phone = "01220210456"
                        },
                        new
                        {
                            Id = new Guid("f1543e8b-4418-4ca8-9d17-223e3eaf7eee"),
                            FirstName = "Omer",
                            LastName = "Ali",
                            Phone = "01220210897"
                        },
                        new
                        {
                            Id = new Guid("f7409cb7-c20d-4f2d-a69a-e695378e8ffc"),
                            FirstName = "Ziad",
                            LastName = "Amr",
                            Phone = "01120210827"
                        });
                });

            modelBuilder.Entity("CourseSystem_DAL.Models.StudentCourse", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CourseId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCourses");

                    b.HasData(
                        new
                        {
                            CourseId = new Guid("1e33dd1b-3a4d-48f5-84c1-565170287dbf"),
                            StudentId = new Guid("3670be78-8f4d-4bbe-b612-3f628e497896")
                        },
                        new
                        {
                            CourseId = new Guid("1e33dd1b-3a4d-48f5-84c1-565170287dbf"),
                            StudentId = new Guid("67fd4e60-40f4-4842-97fa-8c331f862dcf")
                        },
                        new
                        {
                            CourseId = new Guid("2ce2280b-8172-4045-8bdc-270794694177"),
                            StudentId = new Guid("3670be78-8f4d-4bbe-b612-3f628e497896")
                        },
                        new
                        {
                            CourseId = new Guid("2ce2280b-8172-4045-8bdc-270794694177"),
                            StudentId = new Guid("67fd4e60-40f4-4842-97fa-8c331f862dcf")
                        },
                        new
                        {
                            CourseId = new Guid("5ef659b6-d082-41d0-8f5d-984d883a3482"),
                            StudentId = new Guid("3670be78-8f4d-4bbe-b612-3f628e497896")
                        },
                        new
                        {
                            CourseId = new Guid("5ef659b6-d082-41d0-8f5d-984d883a3482"),
                            StudentId = new Guid("67fd4e60-40f4-4842-97fa-8c331f862dcf")
                        });
                });

            modelBuilder.Entity("CourseSystem_DAL.Course", b =>
                {
                    b.HasOne("CourseSystem_DAL.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourseSystem_DAL.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("CourseSystem_DAL.Department", b =>
                {
                    b.HasOne("CourseSystem_DAL.Instructor", "Manager")
                        .WithOne("ManagedDepartment")
                        .HasForeignKey("CourseSystem_DAL.Department", "ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("CourseSystem_DAL.Instructor", b =>
                {
                    b.HasOne("CourseSystem_DAL.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CourseSystem_DAL.Models.CourseSession", b =>
                {
                    b.HasOne("CourseSystem_DAL.Course", "Course")
                        .WithMany("CourseSessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseSystem_DAL.Instructor", "Instructor")
                        .WithMany("CourseSessions")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("CourseSystem_DAL.Models.CourseSessionAttendance", b =>
                {
                    b.HasOne("CourseSystem_DAL.Models.CourseSession", "CourseSession")
                        .WithMany("CourseSessionAttendances")
                        .HasForeignKey("CourseSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseSystem_DAL.Models.Student", "Student")
                        .WithMany("CourseSessionAttendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CourseSystem_DAL.Models.StudentCourse", b =>
                {
                    b.HasOne("CourseSystem_DAL.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseSystem_DAL.Models.Student", "Student")
                        .WithMany("CoursesStudent")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CourseSystem_DAL.Course", b =>
                {
                    b.Navigation("CourseSessions");

                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("CourseSystem_DAL.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("CourseSystem_DAL.Instructor", b =>
                {
                    b.Navigation("CourseSessions");

                    b.Navigation("Courses");

                    b.Navigation("ManagedDepartment");
                });

            modelBuilder.Entity("CourseSystem_DAL.Models.CourseSession", b =>
                {
                    b.Navigation("CourseSessionAttendances");
                });

            modelBuilder.Entity("CourseSystem_DAL.Models.Student", b =>
                {
                    b.Navigation("CourseSessionAttendances");

                    b.Navigation("CoursesStudent");
                });
#pragma warning restore 612, 618
        }
    }
}
