// <auto-generated />
using System;
using CourseSystem_DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseSystem_DAL.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseSystem_DAL.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CourseSystem_DAL.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e65f178-8ad3-442b-859f-48d6d964b044"),
                            FirstName = "Mohamed",
                            LastName = "Ziad",
                            Phone = "01120210123"
                        },
                        new
                        {
                            Id = new Guid("b6e66f14-8e6d-4c03-9c12-753ed9e4f74d"),
                            FirstName = "Ali",
                            LastName = "Basem",
                            Phone = "01220210456"
                        },
                        new
                        {
                            Id = new Guid("8c8e5e8e-2210-4c96-9a78-51f66471627b"),
                            FirstName = "Ahmed",
                            LastName = "Omer",
                            Phone = "01020210789"
                        },
                        new
                        {
                            Id = new Guid("a7405fe2-f9ff-488c-937b-ff60e3e9c24d"),
                            FirstName = "Amr",
                            LastName = "Mohamed",
                            Phone = "01520210246"
                        },
                        new
                        {
                            Id = new Guid("c8b09a7f-0c3a-4a97-b586-55f23cfed9a6"),
                            FirstName = "Omer",
                            LastName = "Ali",
                            Phone = "01220210897"
                        },
                        new
                        {
                            Id = new Guid("30a2d33f-c405-4b72-a7ad-b21e630ada5e"),
                            FirstName = "Basem",
                            LastName = "Ahmed",
                            Phone = "01020210541"
                        },
                        new
                        {
                            Id = new Guid("e44c2c5d-9de9-45b4-814a-03169fc4edd1"),
                            FirstName = "Ziad",
                            LastName = "Amr",
                            Phone = "01120210827"
                        });
                });

            modelBuilder.Entity("CourseSystem_DAL.Department", b =>
                {
                    b.HasOne("CourseSystem_DAL.Instructor", "Manager")
                        .WithOne("ManagedDepartment")
                        .HasForeignKey("CourseSystem_DAL.Department", "ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("CourseSystem_DAL.Instructor", b =>
                {
                    b.HasOne("CourseSystem_DAL.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CourseSystem_DAL.Department", b =>
                {
                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("CourseSystem_DAL.Instructor", b =>
                {
                    b.Navigation("ManagedDepartment");
                });
#pragma warning restore 612, 618
        }
    }
}
